# Model Configuration

# Grid parameters
grid_height: 16
grid_width: 16

# Physical system configuration
physical_system:
  input_dim: 5  # [density, temperature, pressure, u_velocity, v_velocity]
  hidden_dims: [32, 32]
  kernel_size: 3
  num_layers: 2
  learning_rate: 0.001
  physics_weight: 1.0

# Biosphere system configuration
biosphere:
  # State dimensions
  state_dim: 4  # [vegetation_cover, soil_moisture, temperature_mean, pressure_mean]
  action_dim: 2  # [growth_rate, water_consumption]
  hidden_dims: [32, 32]
  learning_rate: 0.001
  reward_scale: 1.0
  
  # Initial ranges
  vegetation_range: [0.0, 1.0]
  soil_moisture_range: [0.0, 1.0]
  growth_rate_range: [-0.1, 0.1]
  water_consumption_range: [0.0, 0.1]

# Geosphere system configuration
geosphere:
  state_dim: 3  # [elevation, erosion_rate, soil_composition]
  action_dim: 2  # [erosion_resistance, deposition_rate]
  hidden_dim: 32
  memory_size: 1000
  batch_size: 32
  learning_rate: 0.0001

# Integration parameters
integration:
  # Time scales (in simulation steps)
  timescales:
    physical: 1
    biosphere: 10
    geosphere: 100
  
  # Component interaction weights
  interaction_weights:
    physical_to_biosphere: 1.0
    physical_to_geosphere: 0.5
    biosphere_to_physical: 0.8
    geosphere_to_physical: 0.3

# Simulation parameters
simulation:
  # Random seed for reproducibility
  seed: 42
  
  # Initial conditions
  initial_conditions:
    # Physical system
    temperature_mean: 288.0  # K
    temperature_std: 5.0
    pressure_mean: 101325.0  # Pa
    pressure_std: 1000.0
    humidity_mean: 0.6
    humidity_std: 0.1
    wind_speed_mean: 5.0  # m/s
    wind_speed_std: 2.0
    
    # Biosphere system
    vegetation_cover_mean: 0.3
    vegetation_cover_std: 0.1
    soil_moisture_mean: 0.4
    soil_moisture_std: 0.1
    
    # Geosphere system
    elevation_mean: 500.0  # m
    elevation_std: 100.0
    
  # Physical constraints
  constraints:
    min_temperature: 200.0  # K
    max_temperature: 330.0
    min_pressure: 50000.0  # Pa
    max_pressure: 110000.0
    min_humidity: 0.0
    max_humidity: 1.0
    max_wind_speed: 50.0  # m/s
    
    min_vegetation: 0.0
    max_vegetation: 1.0
    min_soil_moisture: 0.0
    max_soil_moisture: 1.0
    
    min_elevation: 0.0
    max_elevation: 8848.0  # Mt. Everest height

# Debug parameters
debug:
  print_frequency: 10  # Steps between debug outputs
  save_states: true
  check_constraints: true
  plot_live_updates: false